version: "2.1"
services:
  postgres:
    image: postgres
    build:
      context: postgres/
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flask-restplus-demo
    restart: unless-stopped
    tty: true
